version: '3'
services:
  myapp-mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=tshirt
    ports:
      - 3306:3306
  myapp-main:
    image: abdou80/back_v:02
    depends_on:
      - myapp-mysql
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.servlet.multipart.max-file-size":"3000KB",
        "spring.servlet.multipart.max-request-size":"3000KB",
        "spring.datasource.url":"jdbc:mysql://myapp-mysql:3306/tshirt?serverTimezone=UTC",
        "spring.datasource.username":"root",
        "spring.datasource.password":"test",
        "spring.jpa.hibernate.ddl-auto":"update",
        "spring.jpa.properties.hibernate.dialect":"org.hibernate.dialect.MySQL57Dialect"
         }'
  

